### ISSUE TITLE
Remove package.lock.json from git(Add it to .gitgnore)

### ISSUE THREAD

**Issue by anchal-gupta** [metafy-social/landing-webpage#3]
It is not recommended to add Package.lock.json in git as it gets autogenerated when npm modifies either the node_modules tree or package. json(Here, it will generate when running npm start for the first time).

Solution : `Add package.locj.json to .gitignore`

**Comment by najeebkp** [comment]
hi @anchal-gupta  please assign me this task

**Comment by anchal-gupta** [comment]
Hi @agnxsh, Can you please assign this to me if you find it relevant?

**Comment by agnxsh** [comment]
go for it @anchal-gupta, since you created the issue, i'm preferring

**Comment by anchal-gupta** [comment]
Please find the PR here - https://github.com/metafy-social/landing-webpage/pull/4
